### ISSUE TITLE
photo upload broken

### ISSUE THREAD

**Issue by twinone** [jmendeth/node-botgram#7]
Using the minimal example at the documentation:
```
bot.command("send_drawing", function (msg, reply, next) {
  var stream = fs.createReadStream("./drawing.jpg");
  reply.action("upload_photo");
  reply.photo(stream, "My drawing");
});
```

Replacing the path with my own image produces the following exception:
```
throw new Error("Invalid file ID");
    ^

Error: Invalid file ID
    at Object.resolveFile (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/model.js:789:11)
    at ReplyQueue.photo (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/reply.js:153:16)
    at Bot.<anonymous> (/Users/twinone/dev/fib-bot/index.js:23:11)
    at Bot.<anonymous> (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/message.js:81:22)
    at HandlerQueue.callHandler (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/message.js:57:29)
    at Bot.<anonymous> (/Users/twinone/dev/fib-bot/bot/state.js:22:9)
    at Bot.<anonymous> (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/message.js:81:22)
    at HandlerQueue.callHandler (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/message.js:57:29)
    at Bot.processMessage (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/message.js:46:15)
    at Bot.processUpdate (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/bot.js:245:10)
    at Array.forEach (native)
    at Bot.<anonymous> (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/bot.js:214:12)
    at handleBody (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/bot.js:153:25)
    at IncomingMessage.<anonymous> (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/bot.js:142:33)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

Process finished with exit code 1
```

Also directly passing the path as a string instead of a readable stream has the following error `sendPhoto failed: Bad Request: URL host is empty`:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
TelegramError: sendPhoto failed: Bad Request: URL host is empty
    at TelegramError.Error (native)
    at new TelegramError (/Users/twinone/dev/fib-bot/node_modules/botgram/lib/bot.js:37:20)
```

Can you reproduce this?

**Comment by jmendeth** [comment]
Should be fixed at `master`.

**Comment by twinone** [comment]
Fixed, thanks!
